import { useEffect, useMemo, useState } from 'react'
import type { ChangeEvent, FormEvent } from 'react'
import { departmentOptions, educationLevelOptions, ethnicityOptions, genderOptions, identityTypeOptions, nationalityOptions, positionOptions, type SelectOption } from '../../data/employeeMockData'
import { SelectField } from '../../components/form/SelectField'
import { EmployeeSuccessDialog } from '../../components/employee/EmployeeSuccessDialog'
import { demoEmployeeData, initialFormData, type EmployeeFormData, type FormErrors } from '../../types/employee'

const existingIdentityNumbers = ['079123456789']
const optionName = (list: SelectOption[], id: string) => list.find((option) => option.id === id)?.name ?? '—'
const today = new Date().toISOString().slice(0, 10)

export function CreateEmployeePage() {
  const [formData, setFormData] = useState<EmployeeFormData>(initialFormData); const [errors, setErrors] = useState<FormErrors>({}); const [saving, setSaving] = useState(false); const [toast, setToast] = useState(''); const [showSuccess, setShowSuccess] = useState(false); const [showLeave, setShowLeave] = useState(false)
  const dirty = useMemo(() => JSON.stringify(formData) !== JSON.stringify(initialFormData), [formData])
  useEffect(() => { const saved = localStorage.getItem('employee-demo-draft'); if (saved) { try { setFormData({ ...initialFormData, ...JSON.parse(saved) }) } catch { localStorage.removeItem('employee-demo-draft') } } }, [])
  useEffect(() => { if (!toast) return; const timeout = window.setTimeout(() => setToast(''), 2600); return () => window.clearTimeout(timeout) }, [toast])
  const update = <K extends keyof EmployeeFormData>(key: K, value: EmployeeFormData[K]) => { setFormData((previous) => ({ ...previous, [key]: value })); setErrors((previous) => ({ ...previous, [key]: undefined })) }
  const validate = () => { const next: FormErrors = {}; if (!formData.fullName.trim()) next.fullName = 'Vui lòng nhập họ và tên.'; if (!formData.birthDate || formData.birthDate >= today) next.birthDate = 'Ngày sinh không hợp lệ.'; if (!formData.genderId) next.genderId = 'Vui lòng chọn giới tính.'; if (!formData.identityNumber || (formData.identityType === 'CCCD' && !/^\d{12}$/.test(formData.identityNumber))) next.identityNumber = formData.identityType === 'CCCD' ? 'Số CCCD phải gồm đúng 12 chữ số.' : 'Vui lòng nhập số hộ chiếu.'; else if (formData.identityType === 'CCCD' && existingIdentityNumbers.includes(formData.identityNumber)) next.identityNumber = 'Số CCCD đã tồn tại.'; if (formData.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) next.email = 'Email không đúng định dạng.'; if (formData.phone && !/^0\d{9}$/.test(formData.phone)) next.phone = 'Số điện thoại không đúng định dạng.'; if (!formData.startDate) next.startDate = 'Vui lòng chọn ngày vào làm.'; if (!formData.departmentId) next.departmentId = 'Vui lòng chọn phòng ban.'; if (!formData.positionId) next.positionId = 'Vui lòng chọn chức vụ.'; return next }
  const onSubmit = (event: FormEvent) => { event.preventDefault(); const next = validate(); setErrors(next); const first = Object.keys(next)[0] as keyof EmployeeFormData | undefined; if (first) { document.getElementById(first)?.focus(); return } setSaving(true); window.setTimeout(() => { console.log('Employee demo payload:', formData); setSaving(false); localStorage.removeItem('employee-demo-draft'); setShowSuccess(true) }, 700) }
  const onAvatar = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => update('avatar', String(reader.result)); reader.readAsDataURL(file) }
  const saveDraft = () => { localStorage.setItem('employee-demo-draft', JSON.stringify(formData)); setToast('Đã lưu bản nháp.') }
  const reset = () => { setFormData(initialFormData); setErrors({}); setShowSuccess(false); localStorage.removeItem('employee-demo-draft') }
  return <main><header className="topbar"><div className="brand-mark">H</div><strong>Human Resources</strong><span className="topbar-spacer"/><span className="status-dot"/> <span>CD-01 · Demo</span></header><div className="page-shell">
    <nav className="breadcrumb">Nhân viên <span>/</span> Hồ sơ nhân viên <span>/</span> <b>Thêm mới</b></nav><div className="heading"><div><p className="eyebrow">QUẢN LÝ NHÂN SỰ</p><h1>Thêm mới hồ sơ nhân viên</h1><p>Tạo hồ sơ cơ bản để bắt đầu quy trình tiếp nhận nhân sự.</p></div><button className="button sample" type="button" onClick={() => { setFormData(demoEmployeeData); setErrors({}); setToast('Đã điền dữ liệu mẫu.') }}>Điền dữ liệu mẫu</button></div>
    <ol className="steps" aria-label="Tiến trình tạo hồ sơ"><li className="active" style={{ padding: '10px 12px', borderRadius: 10, background: '#effaf8' }}><i>1</i><span style={{ position: 'relative', zIndex: 1, padding: '0 6px', background: '#effaf8', textDecoration: 'none' }}>Thông tin cá nhân</span></li><li style={{ padding: '10px 12px', borderRadius: 10 }}><i>2</i><span style={{ position: 'relative', zIndex: 1, padding: '0 6px', background: '#fff', textDecoration: 'none' }}>Địa chỉ và liên hệ</span></li><li style={{ padding: '10px 12px', borderRadius: 10 }}><i>3</i><span style={{ position: 'relative', zIndex: 1, padding: '0 6px', background: '#fff', textDecoration: 'none' }}>Thông tin công việc</span></li><li style={{ padding: '10px 12px', borderRadius: 10 }}><i>4</i><span style={{ position: 'relative', zIndex: 1, padding: '0 6px', background: '#fff', textDecoration: 'none' }}>Xác nhận</span></li></ol>
    <form onSubmit={onSubmit}><section className="form-section"><div className="section-title"><span className="section-number">01</span><div><h2>Thông tin định danh</h2><p>Thông tin nhận diện và giấy tờ của nhân viên.</p></div></div><div className="section-content identity-layout"><div className="avatar-field"><label>Ảnh nhân viên</label><div className="avatar-preview">{formData.avatar ? <img src={formData.avatar} alt="Ảnh xem trước"/> : <span>Ảnh<br/>đại diện</span>}</div><label className="upload-button" htmlFor="avatar">Tải ảnh lên</label><input id="avatar" type="file" accept="image/*" onChange={onAvatar}/><small>PNG, JPG · tối đa 5 MB</small></div><div className="fields-grid"> <TextField id="fullName" label="Họ và tên" required value={formData.fullName} error={errors.fullName} onChange={(value) => update('fullName', value)}/><TextField id="birthDate" type="date" label="Ngày sinh" required value={formData.birthDate} error={errors.birthDate} onChange={(value) => update('birthDate', value)}/><SelectField id="genderId" label="Giới tính" required value={formData.genderId} placeholder="-- Chọn giới tính --" options={genderOptions} helperText="Dữ liệu lấy từ Danh mục Giới tính (15)" error={errors.genderId} onChange={(value) => update('genderId', value)}/><SelectField id="identityType" label="Loại giấy tờ" required value={formData.identityType} placeholder="-- Chọn loại giấy tờ --" options={identityTypeOptions} onChange={(value) => update('identityType', value as EmployeeFormData['identityType'])}/><TextField id="identityNumber" label={formData.identityType === 'CCCD' ? 'Số CCCD' : 'Số hộ chiếu'} required value={formData.identityNumber} error={errors.identityNumber} onChange={(value) => update('identityNumber', value)} placeholder={formData.identityType === 'CCCD' ? 'Nhập 12 chữ số' : 'Nhập số hộ chiếu'}/><SelectField id="ethnicityId" label="Dân tộc" value={formData.ethnicityId} placeholder="-- Chọn dân tộc --" options={ethnicityOptions} onChange={(value) => update('ethnicityId', value)}/><SelectField id="nationalityId" label="Quốc tịch" required value={formData.nationalityId} placeholder="-- Chọn quốc tịch --" options={nationalityOptions} onChange={(value) => update('nationalityId', value)}/></div></div></section>
      <section className="form-section"><div className="section-title"><span className="section-number">02</span><div><h2>Địa chỉ và liên hệ</h2><p>Thông tin để trao đổi và liên lạc khi cần thiết.</p></div></div><div className="section-content fields-grid narrow"><TextField id="phone" label="Số điện thoại" value={formData.phone} error={errors.phone} onChange={(value) => update('phone', value)} placeholder="Ví dụ: 0901234567"/><TextField id="email" type="email" label="Email cá nhân" value={formData.email} error={errors.email} onChange={(value) => update('email', value)} placeholder="ten@domain.com"/><TextArea id="currentAddress" label="Địa chỉ hiện tại" value={formData.currentAddress} onChange={(value) => update('currentAddress', value)} /></div></section>
      <section className="form-section"><div className="section-title"><span className="section-number">03</span><div><h2>Thông tin công việc ban đầu</h2><p>Thiết lập vị trí và đơn vị công tác khi bắt đầu.</p></div></div><div className="section-content fields-grid narrow"><TextField id="startDate" type="date" label="Ngày vào làm" required value={formData.startDate} error={errors.startDate} onChange={(value) => update('startDate', value)}/><SelectField id="departmentId" label="Phòng ban" required value={formData.departmentId} placeholder="-- Chọn phòng ban --" options={departmentOptions} helperText="Dữ liệu lấy từ Danh mục Phòng ban (60)" error={errors.departmentId} onChange={(value) => update('departmentId', value)}/><SelectField id="positionId" label="Chức vụ" required value={formData.positionId} placeholder="-- Chọn chức vụ --" options={positionOptions} error={errors.positionId} onChange={(value) => update('positionId', value)}/><SelectField id="educationLevelId" label="Trình độ học vấn" value={formData.educationLevelId} placeholder="-- Chọn trình độ học vấn --" options={educationLevelOptions} onChange={(value) => update('educationLevelId', value)}/></div></section>
      <div className="form-actions"><button type="button" className="button ghost" onClick={() => dirty ? setShowLeave(true) : setToast('Đã quay lại danh sách nhân viên (demo).')}>Hủy</button><span className="actions-spacer"/><button type="button" className="button secondary" onClick={saveDraft}>Lưu nháp</button><button className="button primary" type="submit" disabled={saving}>{saving ? 'Đang lưu...' : 'Lưu và tiếp tục'} <span>→</span></button></div>
    </form></div>{toast && <div className="toast" role="status">{toast}</div>}{showLeave && <div className="overlay"><div className="dialog confirm"><h2>Rời khỏi màn hình?</h2><p>Bạn có dữ liệu chưa lưu. Bạn có chắc muốn rời khỏi màn hình?</p><div className="dialog-actions"><button className="button secondary" onClick={() => setShowLeave(false)}>Ở lại</button><button className="button danger" onClick={() => { setShowLeave(false); reset() }}>Rời khỏi</button></div></div></div>}{showSuccess && <EmployeeSuccessDialog fullName={formData.fullName} department={optionName(departmentOptions, formData.departmentId)} position={optionName(positionOptions, formData.positionId)} onClose={() => setShowSuccess(false)} onReset={reset}/>}</main>
}

function TextField({ id, label, value, error, onChange, required, type = 'text', placeholder }: { id: string; label: string; value: string; error?: string; onChange: (value: string) => void; required?: boolean; type?: string; placeholder?: string }) { return <div className="field"><label htmlFor={id}>{label}{required && <span className="required"> *</span>}</label><input id={id} type={type} value={value} placeholder={placeholder} className={error ? 'invalid' : ''} onChange={(event) => onChange(event.target.value)}/>{error && <p className="error" role="alert">{error}</p>}</div> }
function TextArea({ id, label, value, onChange }: { id: string; label: string; value: string; onChange: (value: string) => void }) { return <div className="field field-wide"><label htmlFor={id}>{label}</label><textarea id={id} value={value} rows={3} placeholder="Nhập địa chỉ hiện tại" onChange={(event) => onChange(event.target.value)}/></div> }
